/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author James
 */
public class Course extends javax.swing.JFrame {

    /**
     * Creates new form Course
     */
    public Course() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUserQuery = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblIDQuery = new javax.swing.JLabel();
        lblText = new javax.swing.JLabel();
        lblCourseName = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblClass = new javax.swing.JLabel();
        lblWorkshop = new javax.swing.JLabel();
        lblCourse_ID = new javax.swing.JLabel();
        lblIDCo = new javax.swing.JLabel();
        scpTexts = new javax.swing.JScrollPane();
        tblTexts = new javax.swing.JTable();
        scpWorkShops = new javax.swing.JScrollPane();
        tblWorkShops = new javax.swing.JTable();
        scpClasses = new javax.swing.JScrollPane();
        tblClasses = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUserQuery.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblUserQuery.setText("<user>");

        lblUser.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblUser.setText("User:");
        lblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserMouseClicked(evt);
            }
        });

        lblID.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblID.setText("ID:");

        lblIDQuery.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblIDQuery.setText("<id>");

        lblText.setText("Text");

        lblCourseName.setText("<course_name>");

        btnBack.setText("Back");

        lblClass.setText("Classes");

        lblWorkshop.setText("WorkShops");

        lblCourse_ID.setText("<course_ID>");

        lblIDCo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblIDCo.setText("ID:");

        tblTexts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scpTexts.setViewportView(tblTexts);

        tblWorkShops.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scpWorkShops.setViewportView(tblWorkShops);

        tblClasses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scpClasses.setViewportView(tblClasses);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCourseName)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIDCo)
                                .addGap(8, 8, 8)
                                .addComponent(lblCourse_ID)))
                        .addGap(207, 207, 207)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUser)
                            .addComponent(lblID))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUserQuery)
                            .addComponent(lblIDQuery))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack)
                            .addComponent(lblClass)
                            .addComponent(lblWorkshop)
                            .addComponent(lblText)
                            .addComponent(scpTexts, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scpWorkShops, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scpClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCourseName)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCourse_ID)
                            .addComponent(lblIDCo)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblUserQuery)
                            .addGap(32, 32, 32))
                        .addComponent(lblIDQuery))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUser)
                        .addGap(18, 18, 18)
                        .addComponent(lblID)))
                .addGap(32, 32, 32)
                .addComponent(lblText)
                .addGap(18, 18, 18)
                .addComponent(scpTexts, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblClass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblWorkshop)
                .addGap(11, 11, 11)
                .addComponent(scpWorkShops, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        
    }//GEN-LAST:event_lblUserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Course().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblClass;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblCourse_ID;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblIDCo;
    private javax.swing.JLabel lblIDQuery;
    private javax.swing.JLabel lblText;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUserQuery;
    private javax.swing.JLabel lblWorkshop;
    private javax.swing.JScrollPane scpClasses;
    private javax.swing.JScrollPane scpTexts;
    private javax.swing.JScrollPane scpWorkShops;
    private javax.swing.JTable tblClasses;
    private javax.swing.JTable tblTexts;
    private javax.swing.JTable tblWorkShops;
    // End of variables declaration//GEN-END:variables
}
