/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Access.Workshop;

/**
 *
 * @author James
 */
public class Workshops extends javax.swing.JFrame {

    /**
     * Creates new form Workshops
     */
    public Workshops(Workshop w) {
        initComponents();
        Integer id = w.getId();
        lblIDActivityQuery.setText(id.toString());
        lblActivy.setText(w.getActivity());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblIDActivity = new javax.swing.JLabel();
        lblAct = new javax.swing.JLabel();
        cbxClue = new javax.swing.JCheckBox();
        lblActivy = new javax.swing.JLabel();
        btnSolution = new javax.swing.JButton();
        lblIDActivityQuery = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblIDActivity.setText("ID:");

        lblAct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAct.setText("Activity");

        cbxClue.setText("Clue");

        lblActivy.setText("<activity>");

        btnSolution.setText("Show Solution");
        btnSolution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolutionActionPerformed(evt);
            }
        });

        lblIDActivityQuery.setText("<id_activity>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblActivy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cbxClue))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack)
                            .addComponent(lblAct)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIDActivity)
                                .addGap(18, 18, 18)
                                .addComponent(lblIDActivityQuery)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(btnSolution)
                .addGap(159, 159, 159))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDActivity)
                    .addComponent(lblIDActivityQuery))
                .addGap(43, 43, 43)
                .addComponent(lblAct)
                .addGap(18, 18, 18)
                .addComponent(lblActivy, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbxClue)
                .addGap(59, 59, 59)
                .addComponent(btnSolution)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSolutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolutionActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnSolutionActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();//Destruye la ventana
        Course co = new Course(null); //
        co.setVisible(true); //Muestra venta Course
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSolution;
    private javax.swing.JCheckBox cbxClue;
    private javax.swing.JLabel lblAct;
    private javax.swing.JLabel lblActivy;
    private javax.swing.JLabel lblIDActivity;
    private javax.swing.JLabel lblIDActivityQuery;
    // End of variables declaration//GEN-END:variables
}
